module.exports = [
  {
    ignores: ["node_modules/**", "playwright-report/**", "test-results/**", "coverage/**"],
  },
  {
    files: ["*.js", "modules/*.js", "scripts/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        Blob: "readonly",
        console: "readonly",
        document: "readonly",
        FormData: "readonly",
        globalThis: "readonly",
        matchMedia: "readonly",
        navigator: "readonly",
        Node: "readonly",
        RadioNodeList: "readonly",
        self: "readonly",
        setTimeout: "readonly",
        URL: "readonly",
        window: "readonly",
        CATEGORIES: "readonly",
        CATEGORY_BY_INGREDIENT: "readonly",
        INGREDIENT_TAGS: "readonly",
        NUTRITION: "readonly",
        PROTEINS: "readonly",
        RECIPES: "readonly",
        averageMacros: "readonly",
        clamp: "readonly",
        cloneRecipe: "readonly",
        ingredientGrams: "readonly",
        integerInRange: "readonly",
        macrosForDay: "readonly",
        macrosForMeal: "readonly",
        normalizeMealPortion: "readonly",
        normalizedProteinGoal: "readonly",
        nutritionUnit: "readonly",
        portionLimits: "readonly",
        proteinInputBounds: "readonly",
        scaleMeal: "readonly",
        scaleMealsToTargets: "readonly",
        supplementalPowderIngredient: "readonly",
        targetFitScore: "readonly",
        targetResults: "readonly",
      },
    },
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-new-native-nonconstructor": "error",
      "no-obj-calls": "error",
      "no-promise-executor-return": "error",
      "no-prototype-builtins": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
  {
    files: ["tests/**/*.js", "playwright.config.js", "eslint.config.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        Buffer: "readonly",
        __dirname: "readonly",
        module: "readonly",
        process: "readonly",
        require: "readonly",
      },
    },
  },
];
